name: CMake on MacOS

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Install dependencies
      run: |
          brew update
          brew install cgal boost eigen tbb python3 qt6
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure with CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: List output
      run: ls -R build

