name: CMake on Windows

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build-arch:
    runs-on: windows-latest

    steps:
    - name: Install dependencies
      run: |
        choco install boost cgal eigen tbb qt6 --no-progress -y
        shell: cmd

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}


