name: CMake on Arch Linux

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm cmake git base-devel qt6-base
        pacman -S --noconfirm boost cgal qt6 eigen

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}


