name: Release build on Windows

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: windows-latest

    steps:
    - name: Install dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat

        set PATH=%PATH%;%CD%\vcpkg
        vcpkg.exe update
        vcpkg.exe install boost:x64-windows cgal:x64-windows eigen3:x64-windows python3:x64-windows qtbase:x64-windows python3:x64-windows usd:x64-windows

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run build script
      run: shell\build.bat

    - name: List output
      run: ls -R build

